events {}

http {
    include /etc/nginx/mime.types;

    server {
        listen 8080;
        server_name localhost;

        # 1. Servir le site web
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        # 2. Faire le pont vers l'API Node.js
        location /api/ {
            proxy_pass http://node_backend:3000/api/;
        }
    }
}
